version: '3.8'

services:
  little-fashion:
    build: 
      context: .
      dockerfile: Dockerfile
    container_name: little-fashion-app
    ports:
      - "8080:8080"
    restart: unless-stopped
    environment:
      - NGINX_HOST=localhost
      - NGINX_PORT=8080
    healthcheck:
      test: ["CMD", "wget", "--quiet", "--tries=1", "--spider", "http://localhost:8080"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.little-fashion.rule=Host(`localhost`)"
      - "traefik.http.services.little-fashion.loadbalancer.server.port=8080"